package at.codefabrik.Springreactivevuejs.product.service.product;

import at.codefabrik.Springreactivevuejs.product.entity.MoneySymbol;
import at.codefabrik.Springreactivevuejs.product.entity.Product;
import at.codefabrik.Springreactivevuejs.product.entity.ProductEs;
import at.codefabrik.Springreactivevuejs.product.entity.ProductImage;
import at.codefabrik.Springreactivevuejs.product.model.ProductSellerResponse;
import at.codefabrik.Springreactivevuejs.product.model.product.ProductDetailsResponse;
import at.codefabrik.Springreactivevuejs.product.model.product.ProductResponse;
import at.codefabrik.Springreactivevuejs.product.model.product.ProductSaveRequest;
import at.codefabrik.Springreactivevuejs.product.repo.mongo.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.util.stream.Collectors;

import static java.util.stream.Collectors.toList;


@Service
@RequiredArgsConstructor
public class ProductService {
    private final ProductRepository productRepository;
    private final ProductEsService productEsService;
    private final ProductImageService productImageService;
    private final ProductPriceService productPriceService;
    private final ProductAvailableService productAvailableService;
    private final ProductFreeDeliveryService productFreeDeliveryService;
    private final ProductAmountService productAmountService;

    /***
     *public Flux<Product> getAllProducts() {
     *         return productESRepository.findAll();
     */
    public Flux<ProductResponse> getAllProducts() {
        return productEsService.findAll().map(this::mapToDto);
    }

    public ProductResponse save(ProductSaveRequest request) {
        // Implementation for saving a product
        Product product = Product.builder()
                //.id(request.getId()) // ID is usually generated by the database
                .name(request.getName())
                //.code(request.getCode())
                .code("PRD-" + System.currentTimeMillis()) // Example code generation
                .description(request.getDescription())
                .companyId(request.getSellerId())
                .categoryId(request.getCategoryId())
                .features(request.getFeatures())
                /**
                 .productImage(request.getImages().stream().map(imgUrl -> {)
                 ProductImage img = new ProductImage();
                 img.setUrl(imgUrl);
                 return img;
                 }).toList())
                 **/
                .productImage(request.getImages().stream().map(item -> new ProductImage(ProductImage.ImageType.THUMBNAIL, item)).collect(toList()))
                //.productImage(request.getImages().stream().map(item->new ProductImage(ProductImage.ImageType.THUMBNAIL, item)).collect(Collectors.toList()))
                .priceMap(request.getPriceMap())
                .active(true) // Assuming new products are active by default
                .build();
        product = productRepository.save(product).block(); //productEsService.saveNewProduct(product);
        return this.mapToDto(productEsService.saveNewProduct(product).block()); // Replace with actual saved product response
        //1-Schreib zu Mongo und ES, Abfrage von ES, update zu Es
        //2-Cacllulate Price and save to Mongo
        //3-Update Redis Cache. Bring von Redis, was geupdated werden muss.
        //4-Verwandeln zu Response-Objekt
    }

    private ProductResponse mapToDto(ProductEs productEs) {
        if (productEs == null) {
            return null;
        }
        //BigDecimal productPrice = productPriceService.getByMoneyType(productEs.getId(), MoneySymbol.CHF);
        //anstatt PoductPrice.java wird ein Field priceMap benutzt. Deswegen brauchen wir diese Zeile nicht mehr.

        //Safely exatract CHF price from price map keyed by MoneySymbol
        BigDecimal chfPrice = null;
        BigDecimal eurPrice = null;
        if(productEs.getPriceMapEs() != null) {
            chfPrice = productEs.getPriceMapEs().get(MoneySymbol.CHF);
            //eurPrice = productEs.getPriceMapEs().get(MoneySymbol.EUR);
        }

        ProductResponse response = ProductResponse.builder()
                .id(productEs.getId())
                .name(productEs.getName())
                .code(productEs.getCode())
                .description(productEs.getDescription())
                .seller(ProductSellerResponse.builder().id(productEs.getSeller().getId()).name(productEs.getSeller().getName()).build())//.companyId(productEs.getCompanyId())
                .categoryId(productEs.getCategory().getId())
                .features(productEs.getFeatures())
                //.images(productImageService.getProductMainImage().stream().map(ProductImage::getUrl).collect(Collectors.toList()))
                //.image(productImageService.getProductMainImage(productEs.getId()))
                //.image(productEs.getImages().get(0))
                .image(
                        productEs.getImages() != null && !productEs.getImages().isEmpty()
                                ? productEs.getImages().get(0)
                                : "https://placehold.co/400x300?text=Test+Bild"
                )

                .available(productAvailableService.getByProductId(productEs.getId()))
                .freeDelivery(productFreeDeliveryService.getAvailable(productEs.getId(), productEs.getPriceMapEs().get("CHF"), MoneySymbol.CHF))
                .deliveryIn(productFreeDeliveryService.getDeliveryInfo(productEs.getId()))
                //.price(price != null ? price.getPrice() : null)
                //.price(productPriceService.getByMoneyType(productEs.getId(), MoneySymbol.CHF))
                .price(chfPrice)
                //.price(eurPrice)
                //.price(productEs.getPriceMapEs().get(MoneySymbol.CHF.getSymbol()))
                //TODO: Über Client request sollte validiert werden, welche Währung gewünscht ist.
                //.moneySymbol(price != null ? price.getMoneySymbol() : null)
                .moneyType(MoneySymbol.CHF.getSymbol())
                //.moneyType(MoneySymbol.EUR.getSymbol())
                .active(productEs.isActive())
                .build();
        return response;
    }

    public Mono<Long> count(){ // Zählt die Anzahl der Produkte in der MongoDB
        return productRepository.count();
    }

    public Mono<ProductDetailsResponse> getProductDetails(String id) {
        return this.mapToDto(productEsService.findById(id));
    }

    public Mono<ProductDetailsResponse> mapToDto(Mono<ProductEs> productEsMono) {
        return productEsMono.map(item ->{
            BigDecimal chfPrice = null;
            BigDecimal eurPrice = null;
            if (item.getPriceMapEs() != null) {
                chfPrice = item.getPriceMapEs().get(MoneySymbol.CHF);
                //eurPrice = item.getPriceMapEs().get(item.getPriceMapEs().get("EUR"));
            }
            return ProductDetailsResponse.builder()
                    .id(item.getId())
                    .name(item.getName())
                    .description(item.getDescription())
                    .features(item.getFeatures())
                    .categoryId(item.getCategory().getId())
                    .seller(ProductSellerResponse.builder()
                            .id(item.getSeller().getId())
                            .name(item.getSeller().getName())
                            .build())
                    .images(item.getImages())
                    .available(productAmountService.getByProductId(item.getId()))
                    .freeDelivery(productFreeDeliveryService.getAvailable(item.getId(), chfPrice, MoneySymbol.CHF))
                    .deliveryIn(productFreeDeliveryService.getDeliveryInfo(item.getId()))
                    //.price(productPriceService.getByMoneyType(item.getId(), MoneySymbol.CHF))
                    //.price(item.getPrices().get("CHF"))
                    //.price(item.getPriceMapEs().get(MoneySymbol.CHF))
                    .price(chfPrice)
                    //.price(eurPrice)
                    .moneyType(MoneySymbol.CHF.getSymbol())
                    .build();
        });
    }
}
